# DataFrame과 List, Dictionary, ndarray 상호 변환

## 1. 1차원 데이터를 Dataframe으로 변환

class pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)[source]

In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

In [4]:
# 1차원 리스트 생성
col_name1 = ['col_1']
list1 = [1, 2, 3]
print(list1, type(list1))

[1, 2, 3] <class 'list'>

In [7]:
# ndarray로 변환
array1 = np.array(list1)
print(array1, type(array1))

[1 2 3] <class 'numpy.ndarray'>

In [12]:
# list1, array1을 dataframe으로 변환(생성)
df1_1 = pd.DataFrame(list1, columns = col_name1, index = (0, 0 ,0))
df1_2 = pd.DataFrame(array1, columns = col_name1)
print(df1_1)
print('-'*30)
print(df1_2)

   col_1
0      1
0      2
0      3
------------------------------
   col_1
0      1
1      2
2      3

## 2. 2차원 데이터를 DataFrame으로 변환

In [15]:
# 컬럼명 생성
col_names = ['col1', 'col2', 'col3']
col_names

['col1', 'col2', 'col3']

In [16]:
# 2차원 리스트 생성
list2 = [[1, 2, 3],[4, 5, 6]]

In [18]:
# list2 ndarray로 변환
array2 = np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# list2, arrya2를 dataframe으로 변환
df2_1 = pd.DataFrame(list2, columns = col_names)
df2_2 = pd.DataFrame(array2, columns = col_names)
print(df2_1)
print('-'* 30)
print(df2_2)

   col1  col2  col3
0     1     2     3
1     4     5     6
------------------------------
   col1  col2  col3
0     1     2     3
1     4     5     6

## 3. 딕셔너리를 DataFrame으로 변환

In [22]:
# dictionary 생성
dict1 = {
    'col1' : [1, 2, 3],
    'col2' : [4, 5, 6],
    'col3' : [7, 8, 9]
}
dict1

{'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}

In [24]:
# dataframe으로 dictionary 변환
df_dict1 = pd.DataFrame(dict1)
df_dict1

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9

## 4. DataFrame을 ndarray, list, dictionary로 변환

In [30]:
# 각 df_dict1f를 array, list로 전합 / DataFrame.value > Numpy.tolist() > list 
list3 = df_dict1.values.tolist()
print(type(list3), '\n', list3)

<class 'list'>
 [[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [33]:
# df_dict1 데이터프레임을 dictionary로 변환
dict3 = df_dict1.to_dict()
print(type(dict3), '', dict3)

<class 'dict'>  {'col1': {0: 1, 1: 2, 2: 3}, 'col2': {0: 4, 1: 5, 2: 6}, 'col3': {0: 7, 1: 8, 2: 9}}

## 5. shape 속성 정리

- python List : Attribute Error
- python Dictionary : Attribute Error
- Numpy ndarray : 사용 가능
- Pandas DataFrame : 사용 가능
- Pnadas Series : 사용 가능

In [ ]:
# List 생성
print(type(list1), list1)
print(f"shape : {list1.shape}") # ❌ 'list object'는 shape라는 속성을 가지고 있지 않음

In [ ]:
# Dictionary 생성
print(type(dict1), dict1)
print(f"shape : {dict1.shape}") # ❌ 'dict object'는 shape라는 속성을 가지고 있지 않음

In [40]:
# array
print(type(array1), array1)
print(f"shape : {array1.shape}")

<class 'numpy.ndarray'> [1 2 3]
shape : (3,)

In [43]:
# DataFrame
print(type(df_dict1), df_dict1)
print(f"shape : {df_dict1.shape}")

<class 'pandas.core.frame.DataFrame'>    col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
shape : (3, 3)

## 6. DataFrame 컬럼 데이터 생성 및 수정

#### 타이타닉 데이터 셋 로드

In [45]:
titanic_df = pd.read_csv('data/titanic/train.csv')
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [48]:
# 상위 5개의 데이터셋 조회
titanic_df.head() # 무조건 외우기 - Default : 5개

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [49]:
# 하위 5개의 데이터셋 조회
titanic_df.tail() # 무조건 외우기 - Default : 5개

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [52]:
# 데이터셋 기본정보 조회
titanic_df.info() # .info()도 외우도록 해야 함

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [55]:
# 데이터셋 수치 정보 조회
titanic_df.describe() # .describe()도 외워야 함
# 수치 데이터만 출력하기 때문에 int타입 혹은 float타입의 컬럼만 출력됨

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [64]:
# Age_0 컬럼 추가
# titanic_df.info()
titanic_df['Age_0'] = 0 # 컬럼이 존재하면 값을 수정한다, 그렇지 않을 경우 새로운 컬럼을 추가한다.

In [65]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Age_0        891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

In [71]:
# Age_by_10 컬럼 추가, Age * 10 값 저장
titanic_df['Age_by_10'] = titanic_df['Age']*10

In [72]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Age_0        891 non-null    int64
 13  Age_by_10    714 non-null    float64
dtypes: float64(3), int64(6), object(5)
memory usage: 97.6+ KB

In [ ]:
# 일부 컬럼 조회
# titanic_df['Age', 'Age_0']

In [100]:
# Family_no 컬럼 추가, SibSp 컬럼 + Parch 컬럼 값 합계 + 1
titanic_df.info()
titanic_df['Family_no'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Age_by_10    714 non-null    float64
dtypes: float64(3), int64(5), object(5)
memory usage: 90.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Age_by_10    714 non-null    float64
 13  Family_no    891 non-null    int64
dtypes: float64(3), int64(6), object(5)
memory usage: 97.6+ KB

In [101]:
titanic_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_by_10,Family_no
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S,270.0,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S,190.0,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S,NaN,4
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C,260.0,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q,320.0,1

## 7. DataFrame 데이터 삭제
- drop(컬럼리스트, axis)

In [84]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Age_0        891 non-null    int64
 13  Age_by_10    714 non-null    float64
dtypes: float64(3), int64(6), object(5)
memory usage: 97.6+ KB

In [90]:
# Age_0 삭제
td_drop = titanic_df.drop('Age_0', axis=1) # axis=0 행 기준 실행 시 Error 발생, axis=1로 실행해야 함

In [94]:
titanic_df.head() # Age_0 객체 존재

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,350.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,350.0

In [95]:
td_drop.head() # Age_0 객체 존재하지 않음

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_by_10
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,220.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,380.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,260.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,350.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,350.0

In [97]:
# 원본 데이터셋 (titanic_df)의 Age_0 컬럼 삭제 후 반영
titanic_df.drop('Age_0', axis=1, inplace=True)

In [99]:
titanic_df.info() # Age_0 컬럼 삭제 -> 원본에 반영됨

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Age_by_10    714 non-null    float64
dtypes: float64(3), int64(5), object(5)
memory usage: 90.6+ KB

In [102]:
# 다중 컬럼 삭제 - Age_by_10 + family_no
titanic_df.drop(['Age_by_10', 'Family_no'], axis=1, inplace=True)

In [103]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [104]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [108]:
titanic_df.drop(0) # index 행, axis=0, inplace==False 새로운 객체 반환

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [110]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [111]:
# 0, 1, 2 인덱스 사제, 원본에 반영
titanic_df.drop([0, 1, 2], axis=0, inplace=True)
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S