# DataFrame Sort, Aggregation, GroupBy

In [2]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

In [3]:
# Titanic 데이셋 로드
titanic_df = pd.read_csv('data/titanic/train.csv')
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 1. DataFrame 정렬(Sort)

### (1) sort_values()
- DataFrame을 특정 컬럼 기준으로 정렬할 때 사용함
- 문법

  DataFrame.sort_values(by='컬럼리스트', ascending=True)

  ascending=True(오름차순), ascending=False(내림차순)

In [10]:
# Name 기준 오름차순 정렬
td_sort_name = titanic_df.sort_values(by = 'Name')
td_sort_name.reset_index(inplace=True)
td_sort_name.drop(columns='index', axis=1, inplace=True)
td_sort_name

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.5500,NaN,S
1,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.2500,NaN,S
2,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.2500,NaN,S
3,309,0,2,"Abelson, Mr. Samuel",male,30.0,1,0,P/PP 3381,24.0000,NaN,C
4,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
886,287,1,3,"de Mulder, Mr. Theodore",male,30.0,0,0,345774,9.5000,NaN,S
887,283,0,3,"de Pelsmaeker, Mr. Alfons",male,16.0,0,0,345778,9.5000,NaN,S
888,362,0,2,"del Carlo, Mr. Sebastiano",male,29.0,1,0,SC/PARIS 2167,27.7208,NaN,C
889,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
890,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S

In [14]:
# Pclass 컬럼 기준으로 내림차순 정렬 한 후 td_sort_pclass 객체 생성
td_sort_pclass = titanic_df.sort_values(by='Pclass', ascending=False)
# 인덱스 재생성, 현재 인덱스 컬럼저장 x, td_sort_pclass 객체에 반영
td_sort_pclass.reset_index(drop=True, inplace=True)
td_sort_pclass

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,512,0,3,"Webber, Mr. James",male,NaN,0,0,SOTON/OQ 3101316,8.0500,NaN,S
2,501,0,3,"Calic, Mr. Petar",male,17.0,0,0,315086,8.6625,NaN,S
3,502,0,3,"Canavan, Miss. Mary",female,21.0,0,0,364846,7.7500,NaN,Q
4,503,0,3,"O'Sullivan, Miss. Bridget Mary",female,NaN,0,0,330909,7.6292,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
886,103,0,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S
887,711,1,1,"Mayne, Mlle. Berthe Antonine (""Mrs de Villiers"")",female,24.0,0,0,PC 17482,49.5042,C90,C
888,712,0,1,"Klaber, Mr. Herman",male,NaN,0,0,113028,26.5500,C124,S
889,713,1,1,"Taylor, Mr. Elmer Zebley",male,48.0,1,0,19996,52.0000,C126,S
890,446,1,1,"Dodge, Master. Washington",male,4.0,0,2,33638,81.8583,A34,S

In [18]:
# 여러 컬럼 정렬
titanic_df.sort_values(by=['Name', 'Pclass']).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.55,NaN,S
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.25,NaN,S
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.25,NaN,S
308,309,0,2,"Abelson, Mr. Samuel",male,30.0,1,0,P/PP 3381,24.00,NaN,C
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.00,NaN,C

## 2. 집계 함수(Aggregation)

### (1) count()
- 결측치(NaN) 제외
- 실제 데이터 갯수 반환

In [19]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [22]:
titanic_df['Name'].count()

np.int64(891)

In [23]:
titanic_df[['Name', 'Age']].count()

Name    891
Age     714
dtype: int64

### (2) shape
- 전체 데이터 수를 확인하는 작업에서는 count() 보다 shape 사용이 효율적

In [24]:
titanic_df.shape

(891, 12)

In [26]:
titanic_df[['Name', 'Age']].shape

(891, 2)

### (3) mean()
- 평균 계산

In [ ]:
titanic_df.info()

In [39]:
# 나이 컬럼의 평균 계산
print(titanic_df['Age'].mean()) 
print(int(titanic_df['Age'].mean()))        # 소수점 삭제 => int() 타입 변환, 'ceil, floor 함수는 numpy'
print(titanic_df['Age'].mean().astype(int)) # 소수점 삭제 => int() 타입 변환
print(titanic_df['Age'].mean().round())

29.69911764705882
29
29
30.0

In [40]:
# 요금의 평균 계산 - 'Fare' 컬럼
print(titanic_df['Fare'].mean()) 
print(int(titanic_df['Fare'].mean()))        # 소수점 삭제 => int() 타입 변환, 'ceil, floor 함수는 numpy'
print(titanic_df['Fare'].mean().astype(int)) # 소수점 삭제 => int() 타입 변환
print(titanic_df['Fare'].mean().round())

32.204207968574636
32
32
32.0

### (4) sum()
- 합계를 계산하는 함수

In [4]:
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
# Age, Fare 컬럼의 합계
titanic_df['Age'].sum()

np.float64(21205.17)

In [8]:
titanic_df[['Age', 'Fare']].sum()

Age     21205.1700
Fare    28693.9493
dtype: float64

In [10]:
# Age, Fare 컬럼의 합계에 반올림 적용
titanic_df[['Age', 'Fare']].sum().round(1)

Age     21205.2
Fare    28693.9
dtype: float64

### (5) min(), max()
- 최솟값 / 최댓값

In [12]:
# 수치형 데이터 컬럼으 대상으로 최대, 최솟값 조회
t_min = titanic_df['Age'].min()
t_max = titanic_df['Age'].max()
print(t_min, t_max)

0.42 80.0

In [14]:
t2_min = titanic_df[['Age', 'Fare']].min()
t2_max = titanic_df[['Age', 'Fare']].min()
print(t2_min, t2_max)

Age     0.42
Fare    0.00
dtype: float64 Age     0.42
Fare    0.00
dtype: float64

# 3. GroupBy

### groupby()
- 특정 컬럼 기준으로 데이터를 그룹화 할 때 사용
- 문법
    - DataFrame.groupby('컬럼리스트')

In [16]:
# 객실 등급별 인우너수 조회
titanic_df.groupby("Pclass").count()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,,
1,216,216,216,216,186,216,216,216,216,176,214
2,184,184,184,184,173,184,184,184,184,16,184
3,491,491,491,491,355,491,491,491,491,12,491

In [17]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [22]:
# 항구별 승선인원 확인
# titanic_df.head()
titanic_df.groupby(['Embarked', 'Pclass'])[['Pclass', 'Fare']].count()

                 Pclass  Fare
Embarked Pclass
C        1           85    85
         2           17    17
         3           66    66
Q        1            2     2
         2            3     3
         3           72    72
S        1          127   127
         2          164   164
         3          353   353

## 4. agg()
- 집계 함수
- 그룹별 서로 다른 집계함수를 적용할 수 있다

In [26]:
# 전체 데이터 대상, count(), sum()
titanic_df.agg(
    {
        'Pclass' : 'count',
        'Fare' : 'sum'
    }
)

Pclass      891.0000
Fare      28693.9493
dtype: float64

In [28]:
# 항구별 그룹, count(), sum()
titanic_df.groupby('Embarked').agg(
    {
        'Pclass' : 'count',
        'Fare' : 'sum',
        'Age' : 'mean'
    }
).round(2)

          Pclass      Fare    Age
Embarked
C            168  10072.30  30.81
Q             77   1022.25  28.09
S            644  17439.40  29.45

In [29]:
# 객실 등급별 그룹, Age : 최대, Fare : 평균값
titanic_df.groupby(['Pclass']).agg(
    {
        'Age' : 'max',
        'Fare' : 'mean'
    }
)

         Age       Fare
Pclass
1       80.0  84.154687
2       70.0  20.662183
3       74.0  13.675550

In [34]:
# 여러 컬럼에 agg() 함수 적용
titanic_df[['Age', 'Fare']].agg(['max', 'min', 'mean']).round(2)

        Age    Fare
max   80.00  512.33
min    0.42    0.00
mean  29.70   32.20

In [37]:
# 전체 데이터셋 대상, 컬럼별 집계함수를 다르게 적용하고 싶을 때
titanic_df.agg(
    {
        'Age' : 'mean',
        'Fare' : 'sum',
        'Pclass' : 'count'
    }
).round(3)

Age          29.699
Fare      28693.949
Pclass      891.000
dtype: float64