# DataFrame Query, Merge

In [2]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

In [3]:
titanic_df = pd.read_csv('data/titanic/train.csv')

In [4]:
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## 1. Query를 이용한 데이터 조회
- query() : 조건식을 문자열 형식으로 작성하여 조회

In [5]:
exam_df = pd.read_csv('data/exam.csv')

In [7]:
exam_df.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [8]:
# exam_df의 형태, 정보 확인
exam_df.shape

(20, 5)

In [9]:
exam_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       20 non-null     int64
 1   nclass   20 non-null     int64
 2   math     20 non-null     int64
 3   english  20 non-null     int64
 4   science  20 non-null     int64
dtypes: int64(5)
memory usage: 932.0 bytes

In [13]:
# 수학 점수가 70점 이상인 데이터 조회
# math >= 70
exam_df.query('math >= 70')

    id  nclass  math  english  science
6    7       2    80       90       45
7    8       2    90       78       25
14  15       4    75       56       78
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [21]:
# 수학 점수가 70점 이상인 2반 학생들 데이터 조회
# 두 개 이상의 조건 And(&), Or(|)
# math >= 70
exam_df.query('math >= 70 & nclass == 2')

   id  nclass  math  english  science
6   7       2    80       90       45
7   8       2    90       78       25

In [23]:
# 1반 이거나 또는 영어 점수가 80점 이상인 데이터 조회
exam_df.query('nclass == 1 | english >= 80').head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [24]:
# nclass 기준 grouupby
exam_df.query('nclass == 1 | nclass == 3 | nclass ==5')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [27]:
# nclass 기준 grouupby
# exam_df.query('nclass == 1 | nclass == 3 | nclass ==5')
exam_df.query('nclass in [1, 3, 5]')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [29]:
# 1반의 수학, 과학 점수 평균조회
exam_df.query('nclass == 1')[['math', 'science']].mean()

math       46.25
science    61.50
dtype: float64

In [33]:
# 변수를 이용하여 query 조건 생성
a = int(input('반을 입력해주세요'))
exam_df.query('nclass == @a')[['nclass', 'english']]

반을 입력해주세요 1

   nclass  english
0       1       98
1       1       97
2       1       86
3       1       98

### 타이타닉 데이터셋 쿼리 실습

In [34]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [40]:
# 1등급 객실의 승객 정보 조회
titanic_df.query('Pclass == 1')['PassengerId'].count()

np.int64(216)

In [38]:
# 1등급 객실의 승객 정보 조회 - boolean indexing
titanic_df[titanic_df['Pclass'] == 1].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [49]:
# 생존한 여성 승객을 조회
titanic_df[(titanic_df['Survived'] == 1) & (titanic_df['Sex'] == 'female')][['Survived', 'Sex']].count()

Survived    233
Sex         233
dtype: int64

In [52]:
titanic_df.query("Survived == 1 & Sex == 'female'")[['Survived', 'Sex']].count()

Survived    233
Sex         233
dtype: int64

In [56]:
# S, Q 항구에서 탑승한 승객 중 생존자 조회
titanic_df.query('Embarked in ["S", "Q"] & Survived == 1')['Sex'].count()

np.int64(247)

In [60]:
ports = ['S', 'Q']
titanic_df.query('Embarked in @ports & Survived == 1').groupby('Embarked').count()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
Embarked,,,,,,,,,,,
Q,30,30,30,30,30,8,30,30,30,30,2
S,217,217,217,217,217,201,217,217,217,217,80

In [79]:
# query()의 매소드 체이닝
# 1, 2 객실 등급의 남자 승객 조회
titanic_df.query("Pclass in [1, 2]") \
    .query("Sex == 'male'") \
    .query('Age >= 20') \
    .query("Embarked == 'S'").head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S

## 2. Merge
- SQL의 JOIN과 유사함
- inner join
- left join
- right join
- outer join

### (1) inner join
- key를 기준으로 두 개의 DataFrame(Table)에 동일하게 존재하는 데이터를 추출
- 예제) '이름'을 키로 하여 inner join(교집합)

In [80]:
df1 = pd.DataFrame(
    {
        '이름' : ['유재석', '정형돈', '노홍철'],
        '키' : [176, 175, 174]
    }
)

In [83]:
df2 = pd.DataFrame(
    {
        '이름' : ['유재석', '정형돈', '장윤주'],
        '성별' : ['남자', '남자', '여자']
    }
)
df2

    이름  성별
0  유재석  남자
1  정형돈  남자
2  장윤주  여자

In [85]:
# inner join how = 'inner' 기본값
pd.merge(df1, df2)

    이름    키  성별
0  유재석  176  남자
1  정형돈  175  남자

### (2) left outer join
- 왼쪽 에디터셋에 있는 데이터프레임 (테이블)의 키를 기준으로 병합

In [114]:
#df1, df2 데이터프레임 left outer join(inner join + left) 테이블 모든 데이터셋
pd.merge(df1, df2, how= 'left')

    이름    키  나이    주소   직업
0  유재석  176  54  압구정동  개발자
1  정형돈  175  32   개화동  개발자
2  노홍철  174  27    홍대  개발자

### (3) Right Outer Join
- 오른쪽 에디터셋에 있는 데이터프레임 (테이블)의 키를 기준으로 병합

In [115]:
# df1, df2 데이터프레임 Right Outer Join (inner join + right) 테이블 모든 데이터셋
pd.merge(df1, df2, how='right')

    이름    키  나이   주소   직업
0  강호동  180  59   미국  NaN
1  이수근  164  45  캐나다  NaN
2   김C  172  60   호주  NaN

### (4) Full Outer Join
- 키를 기준으로 두 데이터프레임의 존재하는 모든 데이터 기준으로 병함

In [88]:
# full outer join
pd.merge(df1, df2, how='outer')

    이름      키   성별
0  노홍철  174.0  NaN
1  유재석  176.0   남자
2  장윤주    NaN   여자
3  정형돈  175.0   남자

## 3. Concat() 함수를 이용한 데이터 병합

In [91]:
df1 = pd.DataFrame(
    {
        '이름' : ['유재석', '정형돈', '노홍철'],
        '키' : [176, 175, 174],
        '나이' : [54, 32, 27],
        '주소' : ['압구정동', '개화동', '홍대']
    }
)
df1

    이름    키  나이    주소
0  유재석  176  54  압구정동
1  정형돈  175  32   개화동
2  노홍철  174  27    홍대

In [92]:
df2 = pd.DataFrame(
    {
        '이름' : ['강호동', '이수근', '김C'],
        '키' : [180, 164, 172],
        '나이' : [59, 45, 60],
        '주소' : ['미국', '캐나다', '호주']
    }
)
df2

    이름    키  나이   주소
0  강호동  180  59   미국
1  이수근  164  45  캐나다
2   김C  172  60   호주

In [94]:
# df1, df2를 행 기준으로 concat() - 새로운 객체로 생성됨
df_concat = pd.concat([df1, df2], axis=0)
df_concat

    이름    키  나이    주소
0  유재석  176  54  압구정동
1  정형돈  175  32   개화동
2  노홍철  174  27    홍대
0  강호동  180  59    미국
1  이수근  164  45   캐나다
2   김C  172  60    호주

In [95]:
# df_concat 데이터프레임 인덱스 재생성, 기존 인덱스 삭제, 원본 반영
df_concat.reset_index(drop=True, inplace=True)
df_concat

    이름    키  나이    주소
0  유재석  176  54  압구정동
1  정형돈  175  32   개화동
2  노홍철  174  27    홍대
3  강호동  180  59    미국
4  이수근  164  45   캐나다
5   김C  172  60    호주

In [96]:
# df1, df2를 열 기준으로 concat
df_concat1 = pd.concat([df1, df2], axis=1)
df_concat1

    이름    키  나이    주소   이름    키  나이   주소
0  유재석  176  54  압구정동  강호동  180  59   미국
1  정형돈  175  32   개화동  이수근  164  45  캐나다
2  노홍철  174  27    홍대   김C  172  60   호주

In [99]:
# df1 객체에 '직업' 컬럼 추가
df1['직업'] = '개발자'
df1

    이름    키  나이    주소   직업
0  유재석  176  54  압구정동  개발자
1  정형돈  175  32   개화동  개발자
2  노홍철  174  27    홍대  개발자

In [100]:
pd.concat([df1, df2])

    이름    키  나이    주소   직업
0  유재석  176  54  압구정동  개발자
1  정형돈  175  32   개화동  개발자
2  노홍철  174  27    홍대  개발자
0  강호동  180  59    미국  NaN
1  이수근  164  45   캐나다  NaN
2   김C  172  60    호주  NaN

In [104]:
join_concat = pd.concat([df1, df2], join='inner')
join_concat.reset_index(drop=True, inplace=True)
join_concat

    이름    키  나이    주소
0  유재석  176  54  압구정동
1  정형돈  175  32   개화동
2  노홍철  174  27    홍대
3  강호동  180  59    미국
4  이수근  164  45   캐나다
5   김C  172  60    호주

## 4. 파일로 저장
- to_csv(경로, 인코딩, header...)

In [105]:
df_concat

    이름    키  나이    주소
0  유재석  176  54  압구정동
1  정형돈  175  32   개화동
2  노홍철  174  27    홍대
3  강호동  180  59    미국
4  이수근  164  45   캐나다
5   김C  172  60    호주

In [109]:
df_concat.to_csv('data/df_concat.csv', encoding='utf-8', index=False, header=False)

In [113]:
df3 = pd.read_csv('data/df_concat.csv', header=None, names=['이름', '키', '주소', '나이'])
df3

    이름    키  주소    나이
0  유재석  176  54  압구정동
1  정형돈  175  32   개화동
2  노홍철  174  27    홍대
3  강호동  180  59    미국
4  이수근  164  45   캐나다
5   김C  172  60    호주