In [1]:
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import platform

if platform.system() == 'Windows':
    matplotlib.rc('font', family='Malgun Gothic')
elif platform.system() == 'Darwin':
    matplotlib.rc('font', family='AppleGothic')
else:
    matplotlib.rc('font', family='DejaVu Sans')

plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['figure.dpi'] = 100

print('NumPy 버전:', np.__version__)
print('환경 설정 완료')

NumPy 버전: 2.3.5
환경 설정 완료

In [4]:
# [예제 1] 결측값 확인 (code7_1, code7_2)
import pandas as pd
import numpy as np

df = pd.read_csv('data/iris.csv')

# 인위적으로 결측값 주입
df.iloc[0, 1] = pd.NA
df.iloc[0, 2] = pd.NA
df.iloc[1, 2] = np.nan
df.iloc[2, 3] = None

print('컬럼별 결측값 수:')
print(df.isnull().sum())
print()
print('결측값이 있는 행:')
print(df.loc[df.isnull().sum(axis=1) > 0, :])

컬럼별 결측값 수:
Id               0
SepalLengthCm    1
SepalWidthCm     2
PetalLengthCm    1
PetalWidthCm     0
Species          0
dtype: int64

결측값이 있는 행:
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            NaN           NaN            1.4           0.2  Iris-setosa
1   2            4.9           NaN            1.4           0.2  Iris-setosa
2   3            4.7           3.2            NaN           0.2  Iris-setosa

In [10]:
# [예제 2] 데이터 정제
import pandas as pd
import numpy as np

df = pd.read_csv('data/iris.csv')
df.iloc[0, 1] = pd.NA
df.iloc[1, 2] = np.nan

print('정제 전 행 수:', len(df))
df_clean = df.dropna().reset_index(drop=True)  # 결측값 행 제거 + 인덱스 재설정
print('정제 후 행 수:', len(df_clean))
print(df_clean.head())

정제 전 행 수: 150
정제 후 행 수: 148
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   3            4.7           3.2            1.3           0.2  Iris-setosa
1   4            4.6           3.1            1.5           0.2  Iris-setosa
2   5            5.0           3.6            1.4           0.2  Iris-setosa
3   6            5.4           3.9            1.7           0.4  Iris-setosa
4   7            4.6           3.4            1.4           0.3  Iris-setosa

In [15]:
# [예제 3] 이상치 탐지 (code7_4)
import pandas as pd
import numpy as np
from scipy import stats

df = pd.read_csv('data/iris.csv')
sw = df['SepalWidthCm']

# Z-score 방법 (|z| > 2 기준)
z = np.abs(stats.zscore(sw))
outliers_z = sw[z > 2]
print('Z-score 이상치 (|z|>2):')
print(outliers_z.values)

# IQR 방법
Q1 = 2.800000 # sw.quantile(0.25)
Q3 = 3.300000 # sw.quantile(0.75)
IQR = Q3 - Q1
outliers_iqr = sw[(sw < Q1 - IQR*1.5) | (sw > Q3 + IQR*1.5)]
print(f'\nIQR 이상치 (Q1-1.5×IQR={Q1-1.5*IQR:.2f}, Q3+1.5×IQR={Q3+1.5*IQR:.2f}):')
print(outliers_iqr.values)

# 이상치 제거
clean = sw.loc[~sw.isin(outliers_iqr)]
print(f'\n원본 크기: {len(sw)} → 이상치 제거 후: {len(clean)}')

Z-score 이상치 (|z|>2):
[4.  4.4 4.1 4.2 2. ]

IQR 이상치 (Q1-1.5×IQR=2.05, Q3+1.5×IQR=4.05):
[4.4 4.1 4.2 2. ]

원본 크기: 150 → 이상치 제거 후: 146

In [14]:
df['SepalWidthCm'].describe()

count    150.000000
mean       3.054000
std        0.433594
min        2.000000
25%        2.800000
50%        3.000000
75%        3.300000
max        4.400000
Name: SepalWidthCm, dtype: float64

In [20]:
# [예제 4] 정렬 (sort_values), 순위 (rank) (code7_5, code7_6)
import pandas as pd

df = pd.read_csv('data/iris.csv')

# 정렬
print('Sepal_Length 오름차순 상위 5행:')
print(df.sort_values('SepalLengthCm').head())

print('\nSpecies, Sepal_Width 복합 정렬 상위 5행:')
print(df.sort_values(['Species', 'SepalWidthCm']).head())

# 순위
print('\nPetal_Length 오름차순 순위 상위 5:')
print(df['PetalLengthCm'].rank().astype(int).head())

Sepal_Length 오름차순 상위 5행:
    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
13  14            4.3           3.0            1.1           0.1  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa

Species, Sepal_Width 복합 정렬 상위 5행:
    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
41  42            4.5           2.3            1.3           0.3  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa

Petal_Length 오름차순 순위 상위 5:
0    17
1    17
2     8
3    30
4    17
Name: PetalLengthCm, dtype: int64

### groupby 집계

In [21]:
# [ 예제 6 ] groupby
df = pd.read_csv('data/iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [26]:
# 단일 그룹 집계
print('품종별 평균 : ')
display(df.groupby('Species').mean().round(2)) # display : 수식의 print()

품종별 평균 :

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,25.5,5.01,3.42,1.46,0.24
Iris-versicolor,75.5,5.94,2.77,4.26,1.33
Iris-virginica,125.5,6.59,2.97,5.55,2.03

In [29]:
# 다중 그룹 집계
df_mpg = pd.read_csv('data/mpg.csv')
df_mpg.head()
df_mpg.groupby(['cylinders', 'weight']).max()

                   mpg  displacement horsepower  acceleration  model year  \
cylinders weight
3         2124    18.0          70.0         90          13.5          73
          2330    19.0          70.0         97          13.5          72
          2420    23.7          70.0        100          12.5          80
          2720    21.5          80.0        110          13.5          77
4         1613    35.0          72.0         69          18.0          71
...                ...           ...        ...           ...         ...
8         4951    12.0         455.0        225          11.0          73
          4952    12.0         429.0        198          11.5          73
          4955    12.0         383.0        180          11.5          71
          4997    11.0         400.0        150          14.0          73
          5140    13.0         400.0        175          12.0          71

                  origin                  car name
cylinders weight
3         2124         3                 maxda rx3
          2330         3           mazda rx2 coupe
          2420         3             mazda rx-7 gs
          2720         3                mazda rx-4
4         1613         3               datsun 1200
...                  ...                       ...
8         4951         1  buick electra 225 custom
          4952         1  mercury marquis brougham
          4955         1         dodge monaco (sw)
          4997         1          chevrolet impala
          5140         1       pontiac safari (sw)

[355 rows x 7 columns]

### concat & merge

In [30]:
# [예제 7] concat으로 DataFrame 결합 (code7_10)
import pandas as pd

df1 = pd.DataFrame([
                        [169, 58, 1.0], 
                        [172, 73, 1.2], 
                        [184, 82, 0.7]
                    ],
                   columns=['height', 'weight', 'eye'])
df2 = pd.DataFrame([
                        [176, 71, 0.8, 'M'], 
                        [169, 62, 0.7, 'F']
                    ],
                   columns=['height', 'weight', 'eye', 'gender'])

# 행 방향 결합 (같은 컬럼 구조)
df12 = pd.concat([df1, df2]).reset_index(drop=True)
print('행 방향 concat 결과:')
print(df12)

행 방향 concat 결과:
   height  weight  eye gender
0     169      58  1.0    NaN
1     172      73  1.2    NaN
2     184      82  0.7    NaN
3     176      71  0.8      M
4     169      62  0.7      F

In [34]:
# 행 방향으로 결합
df12 = pd.concat([df1, df2]).reset_index(drop=True)
df12

   height  weight  eye gender
0     169      58  1.0    NaN
1     172      73  1.2    NaN
2     184      82  0.7    NaN
3     176      71  0.8      M
4     169      62  0.7      F

In [36]:
# merge
df1 = pd.DataFrame([['a', 90], ['b', 80], ['c', 40]], columns=['name', 'kor'])
df2 = pd.DataFrame([['a', 75], ['b', 60], ['d', 90]], columns=['name', 'math'])
print(df1, '\n', df2)

  name  kor
0    a   90
1    b   80
2    c   40
   name  math
0    a    75
1    b    60
2    d    90

In [41]:
# inner join : 공통 이름 기준
df1.merge(df2, on='name')

  name  kor  math
0    a   90    75
1    b   80    60

In [40]:
# left outer join : df1 기준
df1.merge(df2, how='inner')

  name  kor  math
0    a   90    75
1    b   80    60

In [38]:
# outer join : 전체 포함
pd.merge(df1, df2, how="outer")

  name   kor  math
0    a  90.0  75.0
1    b  80.0  60.0
2    c  40.0   NaN
3    d   NaN  90.0